config/routes.rb
Rails.application.routes.draw do
  resources :proofs
  resources :victims
  resources :waitnesses
  resources :culprits
  resources :the_cases
  resources :police_stations
  resources :governorates
  resources :posts
  #devise_for :users
  devise_for :users, controllers:
  {
    registrations: 'users/registrations', sessions: 'users/sessions'
  }
  get 'users/sign_in'
  get 'habib/login'
  get 'habib/principal'
  get 'habib/welcome'
  #post '/governorates/add_police_station'  
  root to: "habib#principal"
  devise_for :users, skip: [:sessions]
  post '/governorates/add_police_station' , to: 'governorates#add_police_station'
  post '/governorates/insert' , to: 'governorates#insert'
  post '/police_stations/insert' , to: 'police_stations#insert'
  post '/the_cases/insert_proof' , to: 'the_cases#insert_proof'
  post '/the_cases/insert_victim' , to: 'the_cases#insert_victim'
  post '/the_cases/insert_culprit' , to: 'the_cases#insert_culprit'
  post '/the_cases/insert_waitness' , to: 'the_cases#insert_waitness'
    #post 'governorates/:id/insert'
  get 'governorates/new_police_station'
  get 'wanteds/find'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/governorate.rb
class Governorate < ApplicationRecord
	has_many :police_stations
end

app/controllers/governorates_controller.rb
class GovernoratesController < ApplicationController
  before_action :set_governorate, only: [:show, :edit, :update, :destroy]

  # GET /governorates
  # GET /governorates.json
  def index
    @governorates = Governorate.all
  end

  # GET /governorates/1
  # GET /governorates/1.json
  def show
    @governorates=Governorate.find(params[:id])
    @police_stations=@governorates.police_stations
  end

  # GET /governorates/new
  def new
    if current_user.rule == 1
       redirect_to :action => "index"
    else
      @governorate = Governorate.new
    end
  end

  # GET /governorates/1/edit
  def edit
  end

  # POST /governorates
  # POST /governorates.json
  def create
    @governorate = Governorate.new(governorate_params)

    #respond_to do |format|
    @governorate.save
    redirect_to governorates_path #correct the redirect
    #  else
    #    format.html { render :new }
    #    format.json { render json: @governorate.errors, status: :unprocessable_entity }
    #  end
    #end
  end
  
  def insert
    @g=Governorate.find_by_id(params[:id][:id])
    @p=PoliceStation.new
    @p.title=params[:police_station][:title]
    @p.address=params[:police_station][:address]
    @p.postal_code=params[:police_station][:postal_code]
    @p.telephone=params[:police_station][:telephone]
    @p.fax=params[:police_station][:fax]
    @g.police_stations << @p
    redirect_to request.referrer, notice: "New police station added ..."
  end

  # PATCH/PUT /governorates/1
  # PATCH/PUT /governorates/1.json
  def update
    respond_to do |format|
      if @governorate.update(governorate_params)
        format.html { redirect_to @governorate, notice: 'Governorate was successfully updated.' }
        format.json { render :show, status: :ok, location: @governorate }
      else
        format.html { render :edit }
        format.json { render json: @governorate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /governorates/1
  # DELETE /governorates/1.json
  def destroy
    @governorate.destroy
    respond_to do |format|
      format.html { redirect_to governorates_url, notice: 'Governorate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_governorate
      @governorate = Governorate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def governorate_params
      params.require(:governorate).permit(:name, :population, :zone)
    end
    
    def add_police_station
     redirect_to :action=>'show'
    end
    
end

app/helpers/governorates_helper.rb
module GovernoratesHelper
end

app/views/governorates/_form.html.erb
<div style="padding-right: 1px ">
  <div class="padding">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-xs-6">
          <br>
          <br>
          <br>
          <br>
          <br>
          <%= form_with(model: governorate, local: true) do |form| %>
            <% if governorate.errors.any? %>
              <div id="error_explanation">
                <h2>
                  <%= pluralize(governorate.errors.count, "error") %> prohibited this governorate from being saved:
                </h2>
                <ul>
                  <% governorate.errors.full_messages.each do |message| %>
                    <li>
                      <%= message %>
                    </li>
                  <% end %>
                </ul>
              </div>
            <% end %>
          
            <div class="field">
              <%= form.label :name %>
              <%= form.text_field :name, id: :governorate_name , class:"form-control"%>
            </div>
          
            <div class="field">
              <%= form.label :population %>
              <%= form.number_field :population, id: :governorate_population , class:"form-control" %>
            </div>
          
            <div class="field">
              <%= form.label :zone %>
              <%= form.text_field :zone, id: :governorate_zone , class:"form-control"  %>
            </div>
          
            <div class="actions">
              <%= form.submit "Create" , class:"btn btn-lg btn-primary btn-block" %>
            </div>
          <% end %>        
        </div>
        <div class="col-lg-6 col-md-6 col-sm-xs-6">
          <figure>
            <%= image_tag("map_tunisia.jpg", :alt => "rss feed" , class:"float-right") %>
          </figure>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/governorates/edit.html.erb
<h1>Editing Governorate</h1>

<%= render 'form', governorate: @governorate %>

<%= link_to 'Show', @governorate %> |
<%= link_to 'Back', governorates_path %>

app/views/governorates/habib.html.erb
<br>
<br>
the value is <%= @x %>

app/views/governorates/index.html.erb
<!--<p id="notice"><%= notice %></p> -->
<br>
<br>
<center>
  <h1>Governorates</h1>
</center>
<table class="table table-striped table-dark" id="example">
  <thead>
    <tr>
      <th>Name</th>
      <th>Population</th>
      <th>Zone</th>
      <th><center>Show</center></th>
      <th><center>Edit</center></th>
      <th><center>Delete</center></th>
    </tr>
  </thead>

  <tbody>
    <% @governorates.each do |governorate| %>
      <tr>
        <td><%= governorate.name %></td>
        <td><%= governorate.population %></td>
        <td><%= governorate.zone %></td>
        <td>
          <center>
            <%= link_to '', governorate , class:"glyphicon glyphicon-eye-open", target:"_top" %>
          </center>
        </td>
        <td>
          <center>
            <%= link_to '', edit_governorate_path(governorate) , class:"glyphicon glyphicon-pencil" , target:"_top" %>
          </center>
        </td>
        <td>
          <center>
            <%= link_to '', governorate, method: :delete, data: { confirm: 'Are you sure?' } ,class:"glyphicon glyphicon-trash" %>
          </center>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Governorate', new_governorate_path %>
<script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js"></script>
<script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>
<script>
  $("#example").dataTable();
</script>

app/views/governorates/new.html.erb
<h1>Add new governorate</h1>

<%= render 'form', governorate: @governorate %>

<%= link_to 'Back', governorates_path %>

app/views/governorates/new_police_station.html.erb
<br>
<br>
<br>
<br>
<br>dqdq
<%= @u %>

app/views/governorates/show.html.erb
<script>
  $(
    function()
    {
      $("#hide").hide();
    }
   );
  
  $(
    function()
    {
      $('#add_police_station').hide();
    }
  );
  
  $(
    function()
    {
      $("#bt_hide_add_police_station").hide();
    }
  );
  
  $(document).ready
	(
		function()
		{
			$("#bt_show_add_police_station").click
			(
				function()
				{
					$("#add_police_station").show();
          $("#bt_show_add_police_station").hide();
          $("#bt_hide_add_police_station").show();
				}
			);
		}
	);
  $(document).ready
	(
		function()
		{
			$("#bt_hide_add_police_station").click
			(
				function()
				{
					$("#add_police_station").hide();
          $("#bt_show_add_police_station").show();
          $("#bt_hide_add_police_station").hide();
				}
			);
		}
	);
</script>
<script>

</script>
<br><br>
<center>
  <h1>Gouvernorate</h1>
  <p id="notice"><%= notice %></p>
  <table style="border-collapse: collapse; border: 1px solid black; width: 50%; text-align: center;">
    <tr style="border: 1px solid black;">
      <td style="border: 1px solid black;"><strong>Name:</strong></td>
      <td style="border: 1px solid black;"><%= @governorate.name %></td>
    </tr>
    <tr>
      <td style="border: 1px solid black;"><strong>Population:</strong></td>
      <td style="border: 1px solid black;"> <%= @governorate.population %></td>
    </tr>
    <tr style="border: 1px solid black;">
      <td style="border: 1px solid black;"><strong>Zone:</strong></td>
      <td style="border: 1px solid black;"><%= @governorate.zone %></td>
    </tr>
  </table>
  <%= link_to 'Edit', edit_governorate_path(@governorate) %> |
  <%= link_to 'Back', governorates_path %>
</center>

<table id="example">
  <thead>
    <tr>
      <th>Title</th>
      <th>Address</th>
      <th>Postal</th>
      <th>Telephone</th>
      <th>Fax</th>
      <th><center>Show</center></th>
      <th><center>Edit</center></th>
      <th><center>Delete</center></th>
    </tr>
  </thead>
  <tbody>
    <% @police_stations.each do |police_station| %>
       <tr>
          <td><%= police_station.title %></td>
          <td><%= police_station.address %></td>
          <td><%= police_station.postal_code %></td>
          <td><%= police_station.telephone %></td>
          <td><%= police_station.fax %></td>
          <td>
            <center>
              <%= link_to '', police_station , class:"glyphicon glyphicon-eye-open" , target:"_top" %>
            </center>
          </td>
          <td>
            <center>
              <%= link_to '', edit_police_station_path(police_station) , class:"glyphicon glyphicon-pencil" , target:"_top" %>
            </center>
          </td>
          <td>
            <center>
              <%= link_to '', police_station, method: :delete, data: { confirm: 'Are you sure?' } , class:"glyphicon glyphicon-trash" %>
            </center>
          </td>
       </tr>
    <% end %>
  </tbody>
</table>
<button id="bt_show_add_police_station">
  Add new police station
</button>
<button id="bt_hide_add_police_station">
  Hide
</button>
<!-- Add police station  -->
<div class="container">
		<div class="row">
      <div class="col-lg-4 col-md-4 col-sm-xs-4" id="add_police_station">
        <center>
          <h3>
            Add new police station
          </h3>
        </center>
        <%= form_tag :action => "insert"  do %>
          <div id="hide">
            <%= text_field 'id' ,'id' , :value=>@governorate.id  %></p>
          </div>
          <table>
            <tr>
              <td><p><label for='title'>Title</label></td>
              <td>
                <%= text_field 'police_station', 'title' , :id=>"title" , class:"form-control" %></p>
              </td>
            </tr>
            <tr>
              <td><p><label for='address'>Address</label></td>
              <td><%= text_field 'police_station', 'address' , :id=>"address" , class:"form-control" %></p></td>
            </tr>
            <tr>
              <td>
                <p><label for="postal_code">Postal code</label>
              </td>
              <td>
                <%= number_field 'police_station', 'postal_code', :id=>"postal_code" , :max=>9999 , :min=>1000 , class:"form-control" %></p>
              </td>
            </tr>
            <tr>
              <td><p><label for="telephone">Telephone</label></td>
              <td>
                <%= telephone_field 'police_station', 'telephone' , :id=>"telephone" , class:"form-control" %></p>
              </td>
            </tr>
            <tr>
              <td>
                <p><label for="fax">Fax</label>
              </td>
              <td>
                <%= telephone_field 'police_station', 'fax' , :id=>"fax" , class:"form-control" %></p>
              </td>
            </tr>
          </table>
          <%= submit_tag "Create" , class:"btn btn-lg btn-primary btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- using javascript -->
<script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js"></script>
<script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>
<script>
  $("#example").dataTable();
</script>