config/routes.rb
Rails.application.routes.draw do
  resources :proofs
  resources :victims
  resources :waitnesses
  resources :culprits
  resources :the_cases
  resources :police_stations
  resources :governorates
  resources :posts
  #devise_for :users
  devise_for :users, controllers:
  {
    registrations: 'users/registrations', sessions: 'users/sessions'
  }
  get 'users/sign_in'
  get 'habib/login'
  get 'habib/principal'
  get 'habib/welcome'
  #post '/governorates/add_police_station'  
  root to: "habib#principal"
  devise_for :users, skip: [:sessions]
  post '/governorates/add_police_station' , to: 'governorates#add_police_station'
  post '/governorates/insert' , to: 'governorates#insert'
  post '/police_stations/insert' , to: 'police_stations#insert'
  post '/the_cases/insert_proof' , to: 'the_cases#insert_proof'
  post '/the_cases/insert_victim' , to: 'the_cases#insert_victim'
  post '/the_cases/insert_culprit' , to: 'the_cases#insert_culprit'
  post '/the_cases/insert_waitness' , to: 'the_cases#insert_waitness'
    #post 'governorates/:id/insert'
  get 'governorates/new_police_station'
  get 'wanteds/find'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/culprit.rb
class Culprit < ApplicationRecord
	belongs_to :the_case
end

app/models/governorate.rb
class Governorate < ApplicationRecord
	has_many :police_stations
end

app/models/police_station.rb
class PoliceStation < ApplicationRecord
	belongs_to :governorate
	has_many :the_cases
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/proof.rb
class Proof < ApplicationRecord
	belongs_to :the_case
end

app/models/the_case.rb
class TheCase < ApplicationRecord
	belongs_to :police_station , :optional => true
	has_many :victims
	has_many :waitnesses
	has_many :proofs
	has_many :culprits
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/victim.rb
class Victim < ApplicationRecord
	belongs_to :the_case , :optional => true
end

app/models/waitness.rb
class Waitness < ApplicationRecord
	belongs_to :the_case
end

app/controllers/habib_controller.rb
class HabibController < ApplicationController
  def index
    @id = params['id']
		@page = params['page']
  end
  
  def welcome
	
  end
  
  def login
  end
end

app/controllers/police_stations_controller.rb
class PoliceStationsController < ApplicationController
  before_action :set_police_station, only: [:show, :edit, :update, :destroy]

  # GET /police_stations
  # GET /police_stations.json
  def index
    @police_stations = PoliceStation.all
  end
  
   def insert
    @p=PoliceStation.find_by_id(params[:id][:id])
    @the_case=TheCase.new
    @the_case.title=params[:the_case][:title]
    @the_case.type_case=params[:the_case][:type_case]
    @the_case.complainant_cin=params[:the_case][:complainant_cin]
    @the_case.complainant_first_name=params[:the_case][:complainant_first_name]
    @the_case.complainant_last_name=params[:the_case][:complainant_last_name]
    @the_case.complainant_telephone=params[:the_case][:complainant_telephone]
    @the_case.location=params[:the_case][:location]
    @the_case.address=params[:the_case][:address]
    @p.the_cases << @the_case
    redirect_to request.referrer, notice: "New case added ..."
   end
   
  # GET /police_stations/1
  # GET /police_stations/1.json
  def show
    @p=PoliceStation.find(params[:id])
    @the_cases=@p.the_cases
  end

  # GET /police_stations/new
  def new
    @police_station = PoliceStation.new
  end

  # GET /police_stations/1/edit
  def edit
  end

  # POST /police_stations
  # POST /police_stations.json
  def create
    @police_station = PoliceStation.new(police_station_params)
    respond_to do |format|
      if @police_station.save
        format.html { redirect_to @police_station, notice: 'Police station was successfully created.' }
        format.json { render :show, status: :created, location: @police_station }
      else
        format.html { render :new }
        format.json { render json: @police_station.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /police_stations/1
  # PATCH/PUT /police_stations/1.json
  def update
    respond_to do |format|
      if @police_station.update(police_station_params)
        format.html { redirect_to @police_station, notice: 'Police station was successfully updated.' }
        format.json { render :show, status: :ok, location: @police_station }
      else
        format.html { render :edit }
        format.json { render json: @police_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /police_stations/1
  # DELETE /police_stations/1.json
  def destroy
    @police_station.destroy
    flash.now[:notice] = 'Police station deleted ...'
    redirect_to request.referrer, notice: "Police station deleted ..."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_police_station
      @police_station = PoliceStation.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def police_station_params
      params.require(:police_station).permit(:title , :address , :postal_code, :telephone, :fax)
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @id = current_user.id
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/culprits_helper.rb
module CulpritsHelper
end

app/helpers/governorates_helper.rb
module GovernoratesHelper
end

app/helpers/police_stations_helper.rb
module PoliceStationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/proofs_helper.rb
module ProofsHelper
end

app/helpers/the_cases_helper.rb
module TheCasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def options_for_types
		['Police', 'National Guard']
	end
end

app/helpers/victims_helper.rb
module VictimsHelper
end

app/helpers/waitnesses_helper.rb
module WaitnessesHelper
end

app/views/police_stations/_form.html.erb
<br>
<br>
<br>
<div style="padding-right: 1px ">
  <div class="padding">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-xs-6">
          <%= form_with(model: police_station, local: true) do |form| %>
            <% if police_station.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(police_station.errors.count, "error") %> prohibited this police_station from being saved:</h2>
          
                <ul>
                <% police_station.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
          
            <div class="field">
              <%= form.label :title %><br>
              <%= form.text_field :title, id: :police_station_address , class:"form-control" %>
            </div>
            
            <div class="field">
              <%= form.label :address %><br>
              <%= form.text_field :address, id: :police_station_address , class:"form-control" %>
            </div>
          
            <div class="field">
              <%= form.label :postal_code %><br>
              <%= form.number_field :postal_code, id: :police_station_postal_code , class:"form-control"%>
            </div>
          
            <div class="field">
              <%= form.label :telephone %><br>
              <%= form.text_field :telephone, id: :police_station_telephone , class:"form-control" %>
            </div>
          
            <div class="field">
              <%= form.label :fax %><br>
              <%= form.text_field :fax, id: :police_station_fax , class:"form-control" %>
            </div>
          
            <div class="actions">
              <%= form.submit %>
            </div>
          <% end %>
        </div>
        <div>
          <figure>
            <%= image_tag("etat.png", :alt => "rss feed" , class:"float-right") %>
          </figure>      
        </div>
      </div>
    </div>
  </div>
</div>

app/views/police_stations/edit.html.erb
<h1>Editing Police Station</h1>

<%= render 'form', police_station: @police_station %>

<%= link_to 'Show', @police_station %> |
<%= link_to 'Back', police_stations_path %>

app/views/police_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Police Stations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Postal code</th>
      <th>Telephone</th>
      <th>Fax</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @police_stations.each do |police_station| %>
      <tr>
        <td><%= police_station.address %></td>
        <td><%= police_station.postal_code %></td>
        <td><%= police_station.telephone %></td>
        <td><%= police_station.fax %></td>
        <td><%= link_to 'Show', police_station %></td>
        <td><%= link_to 'Edit', edit_police_station_path(police_station) %></td>
        <td><%= link_to 'Destroy', police_station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Police Station', new_police_station_path %>

app/views/police_stations/new.html.erb
<h1>New Police Station</h1>

<%= render 'form', police_station: @police_station %>

<%= link_to 'Back', police_stations_path %>

app/views/police_stations/show.html.erb
<br>
<br>
<br>
<br>
<br>
<script>
  $(
    function()
    {
      $("#hide").hide();
    }
   );
  
   $(
    function()
    {
      $('#add_case').hide();
    }
  );
  $(
    function()
    {
      $("#bt_hide_add_case").hide();
    }
  );
  
  $(document).ready
	(
		function()
		{
			$("#bt_show_add_case").click
			(
				function()
				{
					$("#add_case").show();
          $("#bt_show_add_case").hide();
          $("#bt_hide_add_case").show();
				}
			);
		}
	);
  
  $(document).ready
	(
		function()
		{
			$("#bt_hide_add_case").click
			(
				function()
				{
					$("#add_case").hide();
          $("#bt_show_add_case").show();
          $("#bt_hide_add_case").hide();
				}
			);
		}
	);
</script>
<center>
  <h1><%= @police_station.title %></h1>
  <table style="border-collapse: collapse; border: 1px solid black; width: 50%; text-align: center;">
    <tr style="border: 1px solid black;">
      <td style="border: 1px solid black;"><strong>Address</strong></td>
      <td style="border: 1px solid black;"><%= @police_station.address %></td>
    </tr>
    <tr style="border: 1px solid black;">
      <td style="border: 1px solid black;"><strong>Postal code</strong></td>
      <td style="border: 1px solid black;"><%= @police_station.postal_code %></td>
    </tr>
    <tr style="border: 1px solid black;">
      <td style="border: 1px solid black;"><strong>Telephone</strong></td>
      <td style="border: 1px solid black;"><%= @police_station.telephone %></td>
    </tr>
    <tr style="border: 1px solid black;">
      <td style="border: 1px solid black;"><strong>Fax</strong></td>
      <td style="border: 1px solid black;"><%= @police_station.fax %></td>
    </tr>
  </table>
  
  <%= link_to 'Edit', edit_police_station_path(@police_station) %> |
  <%= link_to 'Back', police_stations_path %>
</center>
<br>
<center>
  <h1>
    All cases
  </h1>
</center>
<table class="table table-striped table-dark" id="example">
  <thead>
    <tr>
      <th>
        <center>
          Title
        </center>
      </th>
      <th>
        <center>
          Type
        </center>
      </th>
      <th>
        <center>
          Complainant cin
        </center>
      </th>
      <th>
        <center>
          Complainant first name
        </center>
      </th>
      <th>
        <center>
          Complainant last name
        </center>
      </th>
      <th>
        <center>
          Complainant telephone
        </center>
      </th>
      <th>
        <center>
          Location
        </center>
      </th>
      <th>
        <center>
          Address
        </center>
      </th>
      <th>
        <center>
          Duration
        </center>
      </th>
      <th>
        <center>
          Show
        </center>
      </th>
      <th>
        <center>
          Edit
        </center>
      </th>
      <th>
        <center>
          Delete
        </center>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @the_cases.each do |the_case| %>
      <tr>
        <td>
          <center>
            <%= the_case.title %>
          </center>
        </td>
        <td>
          <center>
            <%= the_case.type_case %>
          </center>
          </td>
        <td>
          <center>
            <%= the_case.complainant_cin %>
          </center>
        </td>
        <td>
          <center>
            <%= the_case.complainant_first_name %>
          </center>
          </td>
        <td>
          <center>
            <%= the_case.complainant_last_name %>
          </center>
          </td>
        <td>
          <center>
            <%= the_case.complainant_telephone %>
          </center>
        </td>
        <td>
          <center>
            <%= the_case.location %>
          </center>
        </td>
        <td>
          <center>
            <%= the_case.address %>
          </center>
        </td>
        <td>
          <center>
            <%= time_ago_in_words(the_case.created_at) %>
          </center>
        </td>
        <td>
          <center>
            <%= link_to '', the_case , class:"glyphicon glyphicon-eye-open" %>
          </center>
        </td>
        <td>
          <center>
            <%= link_to '', edit_the_case_path(the_case) , class:"glyphicon glyphicon-pencil" %>
          </center>
          </td>
        <td>
          <center>
            <%= link_to '', the_case, method: :delete, data: { confirm: 'Are you sure?' } , class:"glyphicon glyphicon-trash" %></td>
          </center>
      </tr>
    <% end %>
  </tbody>
</table>
<button id="bt_show_add_case">
  Add new case
</button>
<button id="bt_hide_add_case">
  Hide
</button>
<!-- Add case  -->
<div class="container">
		<div class="row">
      <div class="col-lg-4 col-md-4 col-sm-xs-4" id="add_case">
        <center>
          <h3>
            Add new case
          </h3>
        </center>
        <%= form_tag :action => "insert"  do %>
          <div id="hide">
            <%= text_field 'id' ,'id' , :value=>@police_station.id  %></p>
          </div>
          <table>
            <tr>
              <td><p><label for='title'>Title</label></td>
              <td>
                <%= text_field 'the_case', 'title' , :id=>"title" , class:"form-control" %></p>
              </td>
            </tr>
            <tr>
              <td><p><label for='type_case'>Type case</label></td>
              <td>
                <%= text_field 'the_case', 'type_case' , :id=>"type_case" , class:"form-control" %></p>
              </td>
            </tr>
            <tr>
              <td><p><label for='complainant_cin'>Complainant CIN</label></td>
              <td>
                <%= text_field 'the_case', 'complainant_cin' , :id=>"complainant_cin" , class:"form-control" %></p>
              </td>
            </tr>
            <tr>
              <td><p><label for='complainant_first_name'>Complainant first name</label></td>
              <td>
                <%= text_field 'the_case', 'complainant_first_name' , :id=>"complainant_first_name" , class:"form-control" %></p>
              </td>
            </tr>
            <tr>
              <td><p><label for='complainant_last_name'>Complainant last name</label></td>
              <td>
                <%= text_field 'the_case', 'complainant_last_name' , :id=>"complainant_last_name" , class:"form-control" %></p>
              </td>
            </tr>
            <tr>
              <td><p><label for='complainant_telephone'>Complainant telephone</label></td>
              <td>
                <%= text_field 'the_case', 'complainant_telephone' , :id=>"complainant_telephone" , class:"form-control" %></p>
              </td>
            </tr>
            <tr>
              <td><p><label for='location'>Location</label></td>
              <td>
                <%= text_field 'the_case', 'location' , :id=>"location" , class:"form-control" %></p>
              </td>
            </tr>
            <tr>
              <td><p><label for='address'>Address</label></td>
              <td>
                <%= text_field 'the_case','address' , :id=>'address' , class:"from-control" %></p>
              </td>
            </tr>
          </table>
          <%= submit_tag "Create" , class:"btn btn-lg btn-primary btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- using javascript -->
<script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js"></script>
<script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>
<script>
  $("#example").dataTable();
</script>