config/routes.rb
Rails.application.routes.draw do
  resources :proofs
  resources :victims
  resources :waitnesses
  resources :culprits
  resources :the_cases
  resources :police_stations
  resources :governorates
  resources :posts
  #devise_for :users
  devise_for :users, controllers:
  {
    registrations: 'users/registrations', sessions: 'users/sessions'
  }
  get 'users/sign_in'
  get 'habib/login'
  get 'habib/principal'
  get 'habib/welcome'
  #post '/governorates/add_police_station'  
  root to: "habib#principal"
  devise_for :users, skip: [:sessions]
  post '/governorates/add_police_station' , to: 'governorates#add_police_station'
  post '/governorates/insert' , to: 'governorates#insert'
  post '/police_stations/insert' , to: 'police_stations#insert'
  post '/the_cases/insert_proof' , to: 'the_cases#insert_proof'
  post '/the_cases/insert_victim' , to: 'the_cases#insert_victim'
  post '/the_cases/insert_culprit' , to: 'the_cases#insert_culprit'
  post '/the_cases/insert_waitness' , to: 'the_cases#insert_waitness'
    #post 'governorates/:id/insert'
  get 'governorates/new_police_station'
  get 'wanteds/find'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/culprit.rb
class Culprit < ApplicationRecord
	belongs_to :the_case
end

app/models/governorate.rb
class Governorate < ApplicationRecord
	has_many :police_stations
end

app/models/police_station.rb
class PoliceStation < ApplicationRecord
	belongs_to :governorate
	has_many :the_cases
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/proof.rb
class Proof < ApplicationRecord
	belongs_to :the_case
end

app/models/the_case.rb
class TheCase < ApplicationRecord
	belongs_to :police_station , :optional => true
	has_many :victims
	has_many :waitnesses
	has_many :proofs
	has_many :culprits
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/victim.rb
class Victim < ApplicationRecord
	belongs_to :the_case , :optional => true
end

app/models/waitness.rb
class Waitness < ApplicationRecord
	belongs_to :the_case
end

app/controllers/habib_controller.rb
class HabibController < ApplicationController
  def index
    @id = params['id']
		@page = params['page']
  end
  
  def welcome
	
  end
  
  def login
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @id = current_user.id
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :content)
    end
end

app/controllers/waitnesses_controller.rb
class WaitnessesController < ApplicationController
  before_action :set_waitness, only: [:show, :edit, :update, :destroy]

  # GET /waitnesses
  # GET /waitnesses.json
  def index
    @waitnesses = Waitness.all
  end

  # GET /waitnesses/1
  # GET /waitnesses/1.json
  def show
  end

  # GET /waitnesses/new
  def new
    @waitness = Waitness.new
  end

  # GET /waitnesses/1/edit
  def edit
  end

  # POST /waitnesses
  # POST /waitnesses.json
  def create
    @waitness = Waitness.new(waitness_params)

    respond_to do |format|
      if @waitness.save
        format.html { redirect_to @waitness, notice: 'Waitness was successfully created.' }
        format.json { render :show, status: :created, location: @waitness }
      else
        format.html { render :new }
        format.json { render json: @waitness.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waitnesses/1
  # PATCH/PUT /waitnesses/1.json
  def update
    respond_to do |format|
      if @waitness.update(waitness_params)
        format.html { redirect_to @waitness, notice: 'Waitness was successfully updated.' }
        format.json { render :show, status: :ok, location: @waitness }
      else
        format.html { render :edit }
        format.json { render json: @waitness.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waitnesses/1
  # DELETE /waitnesses/1.json
  def destroy
    @waitness.destroy
    respond_to do |format|
      format.html { redirect_to waitnesses_url, notice: 'Waitness was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waitness
      @waitness = Waitness.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waitness_params
      params.require(:waitness).permit(:cin, :first_name, :last_name, :telephone, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/culprits_helper.rb
module CulpritsHelper
end

app/helpers/governorates_helper.rb
module GovernoratesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/proofs_helper.rb
module ProofsHelper
end

app/helpers/the_cases_helper.rb
module TheCasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def options_for_types
		['Police', 'National Guard']
	end
end

app/helpers/victims_helper.rb
module VictimsHelper
end

app/helpers/waitnesses_helper.rb
module WaitnessesHelper
end

app/views/waitnesses/_form.html.erb
<br>
<br>
<br>
<br>
<center>
  <h3>Edit this witness</h3>
  <%= form_with(model: waitness, local: true) do |form| %>
    <% if waitness.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(waitness.errors.count, "error") %> prohibited this waitness from being saved:</h2>
  
        <ul>
        <% waitness.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <table>
      <tr>
        <td><%= form.label :cin %></td>
        <td><%= form.text_field :cin, id: :waitness_cin , class:"form-control" %></td>
      </tr>
      <tr>
        <td><%= form.label :first_name %></td>
        <td><%= form.text_field :first_name, id: :waitness_first_name , class:"form-control" %></td>
      </tr>
      <tr>
        <td><%= form.label :last_name %></td>
        <td><%= form.text_field :last_name, id: :waitness_last_name , class:"form-control" %></td>
      </tr>
      <tr>
        <td><%= form.label :telephone %></td>
        <td><%= form.text_field :telephone, id: :waitness_telephone , class:"form-control" %></td>
      </tr>
      <tr>
        <td><%= form.label :content %></td>
        <td><%= form.text_area :content, id: :waitness_content , class:"form-control" %></td>
      </tr>
      <tr>
        <td colspan="2">
          <div class="actions">
            <%= form.submit "Update" , class:"btn btn-lg btn-primary btn-block" %>
          </div>
        </td>
      </tr>
    </table>
    
  <% end %>
</center>

app/views/waitnesses/edit.html.erb
<%= render 'form', waitness: @waitness %>

app/views/waitnesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Waitnesses</h1>

<table>
  <thead>
    <tr>
      <th>Cin</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Telephone</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @waitnesses.each do |waitness| %>
      <tr>
        <td><%= waitness.cin %></td>
        <td><%= waitness.first_name %></td>
        <td><%= waitness.last_name %></td>
        <td><%= waitness.telephone %></td>
        <td><%= waitness.content %></td>
        <td><%= link_to 'Show', waitness %></td>
        <td><%= link_to 'Edit', edit_waitness_path(waitness) %></td>
        <td><%= link_to 'Destroy', waitness, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Waitness', new_waitness_path %>

app/views/waitnesses/new.html.erb
<h1>New Waitness</h1>

<%= render 'form', waitness: @waitness %>

<%= link_to 'Back', waitnesses_path %>

app/views/waitnesses/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<br>
<br>
<center>
  <h3>Information of the witness</h3>
  <table class="tab">
    <tr class="tr">
      <td class="td"><strong>Cin:</strong></td>
      <td class="td"><%= @waitness.cin %></td>
    </tr>
    <tr class="tr">
      <td class="td"><strong>First name:</strong></td>
      <td class="td"><%= @waitness.first_name %></td>
    </tr>
    <tr class="tr">
      <td class="td"><strong>Last name:</strong></td>
      <td class="td"><%= @waitness.last_name %></td>
    </tr>
    <tr class="tr">
      <td><strong>Telephone:</strong></td>
      <td><%= @waitness.telephone %></td>
    </tr>
    <tr class="tr">
      <td class="td"><strong>Content:</strong></td>
      <td class="td"><%= @waitness.content %></td>
    </tr>
  </table>
  <%= link_to 'Edit', edit_waitness_path(@waitness) %> |
  <%= link_to 'Back', waitnesses_path %>
</center>