config/routes.rb
Rails.application.routes.draw do
  resources :proofs
  resources :victims
  resources :waitnesses
  resources :culprits
  resources :the_cases
  resources :police_stations
  resources :governorates
  resources :posts
  #devise_for :users
  devise_for :users, controllers:
  {
    registrations: 'users/registrations', sessions: 'users/sessions'
  }
  get 'users/sign_in'
  get 'habib/login'
  get 'habib/principal'
  get 'habib/welcome'
  #post '/governorates/add_police_station'  
  root to: "habib#principal"
  devise_for :users, skip: [:sessions]
  post '/governorates/add_police_station' , to: 'governorates#add_police_station'
  post '/governorates/insert' , to: 'governorates#insert'
  post '/police_stations/insert' , to: 'police_stations#insert'
  post '/the_cases/insert_proof' , to: 'the_cases#insert_proof'
  post '/the_cases/insert_victim' , to: 'the_cases#insert_victim'
  post '/the_cases/insert_culprit' , to: 'the_cases#insert_culprit'
  post '/the_cases/insert_waitness' , to: 'the_cases#insert_waitness'
    #post 'governorates/:id/insert'
  get 'governorates/new_police_station'
  get 'wanteds/find'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/culprit.rb
class Culprit < ApplicationRecord
	belongs_to :the_case
end

app/models/governorate.rb
class Governorate < ApplicationRecord
	has_many :police_stations
end

app/models/police_station.rb
class PoliceStation < ApplicationRecord
	belongs_to :governorate
	has_many :the_cases
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/proof.rb
class Proof < ApplicationRecord
	belongs_to :the_case
end

app/models/the_case.rb
class TheCase < ApplicationRecord
	belongs_to :police_station , :optional => true
	has_many :victims
	has_many :waitnesses
	has_many :proofs
	has_many :culprits
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/victim.rb
class Victim < ApplicationRecord
	belongs_to :the_case , :optional => true
end

app/models/waitness.rb
class Waitness < ApplicationRecord
	belongs_to :the_case
end

app/controllers/habib_controller.rb
class HabibController < ApplicationController
  def index
    @id = params['id']
		@page = params['page']
  end
  
  def welcome
	
  end
  
  def login
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @id = current_user.id
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :content)
    end
end

app/controllers/proofs_controller.rb
class ProofsController < ApplicationController
  before_action :set_proof, only: [:show, :edit, :update, :destroy]

  # GET /proofs
  # GET /proofs.json
  def index
    @proofs = Proof.all
  end

  # GET /proofs/1
  # GET /proofs/1.json
  def show
  end

  # GET /proofs/new
  def new
    @proof = Proof.new
  end

  # GET /proofs/1/edit
  def edit
  end

  # POST /proofs
  # POST /proofs.json
  def create
    @proof = Proof.new(proof_params)

    respond_to do |format|
      if @proof.save
        format.html { redirect_to @proof, notice: 'Proof was successfully created.' }
        format.json { render :show, status: :created, location: @proof }
      else
        format.html { render :new }
        format.json { render json: @proof.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proofs/1
  # PATCH/PUT /proofs/1.json
  def update
    respond_to do |format|
      if @proof.update(proof_params)
        format.html { redirect_to @proof, notice: 'Proof was successfully updated.' }
        format.json { render :show, status: :ok, location: @proof }
      else
        format.html { render :edit }
        format.json { render json: @proof.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proofs/1
  # DELETE /proofs/1.json
  def destroy
    @proof.destroy
    respond_to do |format|
      format.html { redirect_to proofs_url, notice: 'Proof was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proof
      @proof = Proof.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proof_params
      params.require(:proof).permit(:type_proof, :content)
    end
end

app/controllers/victims_controller.rb
class VictimsController < ApplicationController
  before_action :set_victim, only: [:show, :edit, :update, :destroy]

  # GET /victims
  # GET /victims.json
  def index
    @victims = Victim.all
  end

  # GET /victims/1
  # GET /victims/1.json
  def show
  end

  # GET /victims/new
  def new
    @victim = Victim.new
  end

  # GET /victims/1/edit
  def edit
  end

  # POST /victims
  # POST /victims.json
  def create
    @victim = Victim.new(victim_params)

    respond_to do |format|
      if @victim.save
        format.html { redirect_to @victim, notice: 'Victim was successfully created.' }
        format.json { render :show, status: :created, location: @victim }
      else
        format.html { render :new }
        format.json { render json: @victim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /victims/1
  # PATCH/PUT /victims/1.json
  def update
    respond_to do |format|
      if @victim.update(victim_params)
        format.html { redirect_to @victim, notice: 'Victim was successfully updated.' }
        format.json { render :show, status: :ok, location: @victim }
      else
        format.html { render :edit }
        format.json { render json: @victim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /victims/1
  # DELETE /victims/1.json
  def destroy
    @victim.destroy
    respond_to do |format|
      format.html { redirect_to victims_url, notice: 'Victim was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_victim
      @victim = Victim.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def victim_params
      params.require(:victim).permit(:cin, :first_name, :last_name, :problem, :cause_of_death, :date_of_death)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/culprits_helper.rb
module CulpritsHelper
end

app/helpers/governorates_helper.rb
module GovernoratesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/proofs_helper.rb
module ProofsHelper
end

app/helpers/the_cases_helper.rb
module TheCasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def options_for_types
		['Police', 'National Guard']
	end
end

app/helpers/victims_helper.rb
module VictimsHelper
end

app/helpers/waitnesses_helper.rb
module WaitnessesHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :post_name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<p>The value of user is : <strong><%= @id %></strong></p>
<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/victims/_form.html.erb
<br>
<br>
<center>
  <h2>Edit Victim</h2>
    <%= form_with(model: victim, local: true) do |form| %>
      <% if victim.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(victim.errors.count, "error") %> prohibited this victim from being saved:</h2>
          <ul>
            <% victim.errors.full_messages.each do |message| %>
            <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table>
  <tr>
    <td><%= form.label :cin %></td>
    <td><%= form.text_field :cin, id: :victim_cin , class:"form-control" %></td>
  </tr>
  <tr>
    <td><%= form.label :first_name %></td>
    <td><%= form.text_field :first_name, id: :victim_first_name , class:"form-control" %></td>
  </tr>
  <tr>
    <td><%= form.label :last_name %></td>
    <td><%= form.text_field :last_name, id: :victim_last_name , class:"form-control" %></td>
  </tr>
  <tr>
    <td><%= form.label :problem %></td>
    <td><%= form.text_field :problem, id: :victim_problem , class:"form-control" %></td>
  </tr>
  <tr>
    <td><%= form.label :cause_of_death %></td>
    <td><%= form.text_field :cause_of_death, id: :victim_cause_of_death , class:"form-control" %></td>
  </tr>
  <tr>
    <td><%= form.label :date_of_death %></td>
    <td><%= form.date_select :date_of_death, id: :victim_date_of_death , class:"form-control" %></td>
  </tr>
  <tr>
    <td colspan="2">
      <div class="actions">
        <%= form.submit "Update" , class:"btn btn-lg btn-primary btn-block" %>
      </div>
    </td>
  </tr>
</table>
<% end %>

app/views/victims/edit.html.erb
<%= render 'form', victim: @victim %>

<%= link_to 'Show', @victim %> |
<%= link_to 'Back', victims_path %>

app/views/victims/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Victims</h1>

<table>
  <thead>
    <tr>
      <th>Cin</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Problem</th>
      <th>Cause of death</th>
      <th>Date of death</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @victims.each do |victim| %>
      <tr>
        <td><%= victim.cin %></td>
        <td><%= victim.first_name %></td>
        <td><%= victim.last_name %></td>
        <td><%= victim.problem %></td>
        <td><%= victim.cause_of_death %></td>
        <td><%= victim.date_of_death %></td>
        <td><%= link_to 'Show', victim %></td>
        <td><%= link_to 'Edit', edit_victim_path(victim) %></td>
        <td><%= link_to 'Destroy', victim, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Victim', new_victim_path %>

app/views/victims/new.html.erb
<h1>New Victim</h1>

<%= render 'form', victim: @victim %>

<%= link_to 'Back', victims_path %>

app/views/victims/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<br>
<br>
<center>
  <h3>Informations of victim</h3>
  <table class="tab">
    <tr class="tr">
      <td class="td"><strong>Cin:</strong></td>
      <td class="td"><%= @victim.cin %></td>
    </tr>
    <tr class="tr">
      <td class="td"><strong>First name:</strong></td>
      <td class="td"><%= @victim.first_name %></td>
    </tr>
    <tr class="tr">
      <td class="td"><strong>Last name:</strong></td>
      <td class="td"><%= @victim.last_name %></td>
    </tr>
    <tr class="tr">
      <td class="td"><strong>Problem:</strong></td>
      <td class="td"><%= @victim.problem %></td>
    </tr>
    <tr class="tr">
      <td class="td"><strong>Cause of death:</strong></td>
      <td class="td"><%= @victim.cause_of_death %></td>
    </tr>
    <tr class="tr">
      <td class="td"><strong>Date of death:</strong></td>
      <td class="td"><%= @victim.date_of_death %></td>
    </tr>
  </table>
  <%= link_to 'Edit', edit_victim_path(@victim) %> |
  <%= link_to 'Back', victims_path %>
</center>